import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BotUI from "@/components/BotUI";
import Footer from "@/components/Footer";

const username = 'telegramUsername';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TITA Tapbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header username={username} />
      <BotUI />
      <Footer />
        {children}</body>
    </html>
  );
}
